[package]

name = "handlebars-iron"
version = "0.1.0"
authors = ["Ning Sun <sunng@about.me>"]

[dependencies]

iron = "*"
handlebars = "*"
rustc-serialize = "*"
modifier = "*"
glob = "*"
plugin = "*"
#notify = "*"
